### ISSUE TITLE
python3: ImportError: No module named 'conf'

### ISSUE THREAD

**Issue by nd2s** [by-cx/InvoiceGenerator#8]
```
Traceback (most recent call last):
  File "main.py", line 2, in <module>
      from InvoiceGenerator.api import Invoice, Item, Client, Provider, Creator
  File "/usr/lib/python3.4/site-packages/InvoiceGenerator/api.py", line 6, in <module>
      from conf import _
ImportError: No module named 'conf'
```

**Comment by ashvinkhodifad** [comment]
you are using python 3.x . this problem happened to me on Linux but after using python 2.7.x it started as normal.
